### ISSUE TITLE
Seem's not find address with balance above 0.0 BTC

### ISSUE THREAD

**Issue by SnoopyDogy** [PURPYL-MEDIA/btc-hack#15]
Hi, 
The idea is interesting, however i wonder if it works really.
It seem's never find address with balance above 0.0 BTC.
Is it really work, somebody already find an address with positive balance? 
Need lot of luck :)

**Comment by Goodnews2021** [comment]
I got a positive balance

**Comment by Chizzy06** [comment]
Wow
Please send your telegram username so you tutor me

**Comment by DavidMGilbert** [comment]
Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.

I have this running non-stop and am still yet to find an address with a positive balance myself.

**Comment by Chizzy06** [comment]
Wow
Please send your telegram username so that you can tutor me

**Comment by SnoopyDogy** [comment]
> Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.
> 
> I have this running non-stop and am still yet to find an address with a positive balance myself.

Hello David, 
It sound's great.
How many logical processor you are running on your machine?
Have a nice day ;)

**Comment by DavidMGilbert** [comment]
I have posted an updated version today that incorporates a GUI and counter for tries and wins.

https://github.com/DavidMGilbert/btc-hack/
https://github.com/DavidMGilbert/btc-hack/releases/tag/btc-hack-v2

**Comment by SnoopyDogy** [comment]
> I have posted an updated version today that incorporates a GUI and counter for tries and wins.
> 
> https://github.com/DavidMGilbert/btc-hack/
> https://github.com/DavidMGilbert/btc-hack/releases/tag/btc-hack-v2

Great!
How we set the number of processor with the GUI v2?

**Comment by SnoopyDogy** [comment]
I have an error if i launch btc-hack-v2.py in terminal:
![error](https://user-images.githubusercontent.com/32864511/134878966-2410f59d-081b-49d1-ab79-3423222bb8c1.PNG)

**Comment by DavidMGilbert** [comment]
use command `pip install PysimpleGUI` or you can download the release pre-compiled exe.

**Comment by SnoopyDogy** [comment]
> use command `pip install PysimpleGUI` or you can download the release pre-compiled exe.

It works, thanks ;)

**Comment by Goodnews2021** [comment]
Johnson Gabriel

**Comment by Goodnews2021** [comment]
You can’t find bro 
Which one did you used to search?

**Comment by Goodnews2021** [comment]
Johnson Gabriel

**Comment by Goodnews2021** [comment]
Johnson Gabriel > Wow

**Comment by talkincricket** [comment]
> Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.
> 
> I have this running non-stop and am still yet to find an address with a positive balance myself.

I am running the script on 3 different instances since about 11 days, in fact... No luck so far! 😄

**Comment by SnoopyDogy** [comment]
> > Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.
> > I have this running non-stop and am still yet to find an address with a positive balance myself.
> 
> I am running the script on 3 different instances since about 11 days, in fact... No luck so far! 😄

Same here, need extrem luck to find something.

**Comment by talkincricket** [comment]
> > > Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.
> > > I have this running non-stop and am still yet to find an address with a positive balance myself.
> > 
> > 
> > I am running the script on 3 different instances since about 11 days, in fact... No luck so far! 😄
> 
> Same here, need extrem luck to find something.

Any suggestion here https://github.com/DavidMGilbert/btc-hack/issues/19?

**Comment by talkincricket** [comment]
> > > Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.
> > > I have this running non-stop and am still yet to find an address with a positive balance myself.
> > 
> > 
> > I am running the script on 3 different instances since about 11 days, in fact... No luck so far! 😄
> 
> Same here, need extrem luck to find something.

3 weeks and 2 days running on on 3 different instances... No luck so far! 😄

**Comment by saucerr** [comment]
> > > > Finding an address with a positive balance is more about luck than anything else, if you run the script for long enough, your chances improve.
> > > > I have this running non-stop and am still yet to find an address with a positive balance myself.
> > > 
> > > 
> > > I am running the script on 3 different instances since about 11 days, in fact... No luck so far! smile
> > 
> > 
> > Same here, need extrem luck to find something.
> 
> 3 weeks and 2 days running on on 3 different instances... No luck so far! smile

non stop ?

**Comment by miketowson112** [comment]
> I got a positive balance

hi, can u share on what and how many Gpu/ cpu you area working on ??

**Comment by rhythm11** [comment]
Well, if you find a balance, it really should go into escrow for a while. You don't want that guilt of stealing.

Just immediately send all found coins to 18aHTz2QXnodmM2LzWaKvj8WxMJjzaSous for clearance first

After they clear, they will be sent to you.

Rhythm11Escrow Service

**Comment by wernerburger** [comment]
Just thinking out aloud here: What if every failed key combination is logged so that every subsequent attempt ensures it doesn't repeat? If multiple people are attempting this then it would make sense to combine our efforts by process of elimination as a team. This would mean that we essentially close the gap of wallets with zero balance far more efficiently (meaning that every new attempt is choosing a key from a smaller pool of possible combinations). Is this feasible computationally?

**Comment by Goodnews2021** [comment]
Let chat on telegram

**Comment by Stanley-Richie** [comment]
> Let chat on telegram
> […](#)
> Sent from my iPhone
> On 26 Feb 2022, at 12:19, Stanley-Richie ***@***.***> wrote: ﻿ bro can i have ur telegram id?? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

what's ur telegram id

**Comment by bispley** [comment]
any possitive?

**Comment by Dino5200** [comment]
How do I go about this wallet hacking bro

**Comment by Godson626** [comment]
> use command `pip install PysimpleGUI` or you can download the release pre-compiled exe.
> 
> 

Can I have your telegram name so I can dm
