### ISSUE TITLE
Best settings CPU/Thread...?

### ISSUE THREAD

**Issue by talkincricket** [PURPYL-MEDIA/btc-hack#19]
Could you please advice for best tuning these lines according to these cases?

1. lscpu
- CPU(s): 2
- On-line CPU(s) list: 0,1
- Thread(s) per core: 2
- 

2. lscpu
- CPU(s): 1
- On-line CPU(s) list: 0
- Thread(s) per core: 1

```
pool = ThreadPool(processes = multiprocessing.cpu_count()*2)
pool.map(thread, range(0, 1))
```

**Comment by talkincricket** [comment]
Any advice? 🙃

**Comment by SnoopyDogy** [comment]
No, sorry.
