### ISSUE TITLE
No uppercase letters!

### ISSUE THREAD

**Issue by gogosholo** [PURPYL-MEDIA/btc-hack#20]
There is no uppercase letters on any generated private key. This is not gonna work!

**Comment by DavidMGilbert** [comment]
The first valid private key in hexadecimal is 0000000000000000000000000000000000000000000000000000000000000001 and the last valid private key in hexadecimal is fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140

**and YES, they should all be lowercase.**

This range is defined by the secp256k1 with the ECDSA algorithm, which is the foundation of the Bitcoin technology. 

The Private key you see is this value, the Key you import to your wallet software is the WIF private key.

**Comment by gogosholo** [comment]
Got it. Thanks for clearing that up
