### ISSUE TITLE
I like what I see

### ISSUE THREAD

**Issue by aiobank** [PURPYL-MEDIA/btc-hack#21]
I like what you have created.

Can you make a scanner based off of this article??? https://archive.ph/fG729

**Comment by talkincricket** [comment]
I wanted to propose the same thing after reading https://archive.md/TGjq5

**Comment by SnoopyDogy** [comment]
> I wanted to propose the same thing after reading https://archive.md/TGjq5

Is there new tools according this guide from Avalerion?

**Comment by talkincricket** [comment]
😄 ... no, at least at the moment, as far as I have been able to verify...

**Comment by talkincricket** [comment]
> > I wanted to propose the same thing after reading https://archive.md/TGjq5
> 
> Is there new tools according this guide from Avalerion?

Something here... https://github.com/stateactor/Bitcoin-Key-Compression-Tool
I have some automation ideas but wasn't able to use the tools as I am not so that technical in python... 🤣
