### ISSUE TITLE
Can I change the api from sochain to blockchain… would it increase the probability of getting an address with balance? (As I have demonstrated in the code)

### ISSUE THREAD

**Issue by partyhad** [PURPYL-MEDIA/btc-hack#39]
def get_balance(address):
    time.sleep(0.2) #This is to avoid over-using the API and keep the program running indefinately.
    try:
        response = requests.get("https://blockchain.com/api/v2/address/BTC/" + str(address))
        return float(response.json()['data']['balance']) 
    except:
        return -1

**Comment by DavidMGilbert** [comment]
You can use pretty much any online API you like, I chose sochain because of their free limits. Regardless of which API you use however your odds are going to remain the same because the API is merely providing the balance of a generated address and nothing more.
