### ISSUE TITLE
wallet addresses in hand

### ISSUE THREAD

**Issue by cotlito** [PURPYL-MEDIA/btc-hack#54]
hi i already have the address, how can this be useful ?

**Comment by folajuwon99** [comment]
Hi how did you get a wallet been trying this for a month now and maybe a couple days.. paid for the whole thing from someone else and didn’t know it was free somewhere else.. I know how to pull funds and everything but not just seen a wallet

**Comment by DavidMGilbert** [comment]
It is more about luck with this than anything else. If your lucky enough to generate an address that holds a balance, your in. Could you please share the link with me to where/who that are that are charging for this?

**Comment by folajuwon99** [comment]
It is on Snapchat, I paid nearly £700 for this, and then paid £150 for a bot to help open the wallet and another £100+ for an upgrade almsot £1000 not knowing the program was written by someone else.. I have so much debts I was hoping I was going to make money and clear this off my head I’m basically a student.. got my rent due owe someone money in like some and then he’s asking for more money for updates I don’t know if all the work I do goes to his own system because for a month and some days I haven’t even seen a wallet talk less of $0

**Comment by folajuwon99** [comment]
If you’re on Snapchat I can text you or telegram then to snap if you don’t want to share on here your snap.. I need you to please help me check what was installed for me as well.. he also posted some wallet he got today about 7 and I haven’t gotten any

**Comment by theraw** [comment]
@folajuwon99 there's lots of scams going around these days ppl take code from github and sell it as a private tool and advertise it as a 100% working tool that can help you with your problem. If you purchase something and is not what you expected don't pay any more money for it, the seller is 100% scamming you.

**Comment by folajuwon99** [comment]
@theraw i wouldn’t say the code doesn’t work, as it’s installed and I can see it running on my system I haven’t just been lucky to get a wallet to help me.. I would just like the creator of the code to look through it if there’s any loop holes or someone who’s familiar with it… would really like to get a wallet to help me make some $

**Comment by folajuwon99** [comment]
@theraw do you know any other channels/codes where I can install and make money off it?

**Comment by DavidMGilbert** [comment]
The whole idea of crypto is it's security, this code is merely a demonstration of the potential to obtain duplicate wallet details through the process of creating a wallet address. 

TBH and while I'm not aware of your personal circumstances, I'd suggest you would be better off looking for a legitimate job/profession. You would honestly have a better chance of winning the lottery than finding any substantial wallet details using any app like this.

**Comment by theraw** [comment]
@folajuwon99 i have some wallets that need cracking and haven't had any luck so no ideas i'm sorry

by cracking i mean cracking a wallet with owners consent and getting a share!

**Comment by DavidMGilbert** [comment]
Sorry guys but this isn't really the place to be discussing this. I'm going to remove this thread.
